Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import warnings
from IPython.display import HTML
import requests
from tempfile import mkstemp
from pathlib import Path
import numpy as np
import nibabel as nb

from eddymotion.dmri import DWI
from eddymotion.viz import plot_dwi
from eddymotion.estimator import _advanced_clip

warnings.filterwarnings("ignore")

url = "https://files.osf.io/v1/resources/8k95s/providers/osfstorage/6070b4c2f6585f03fb6123a2"
datapath = Path(mkstemp(suffix=".h5")[1])
if datapath.stat().st_size == 0:
    datapath.write_bytes(
        requests.get(url, allow_redirects=True).content
    )

dmri_dataset = DWI.from_filename(datapath)
datapath.unlink()


def _to_nifti(
    data, affine, filename, clip=True
):
    data = np.squeeze(data)
    if clip:
        data = _advanced_clip(data)
    nb.Nifti1Image(
        data,
        affine,
        None,
    ).to_filename(filename)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 9[0m
[1;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      7[0m [38;5;28;01mimport[39;00m [38;5;21;01mnibabel[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnb[39;00m
[0;32m----> 9[0m [38;5;28;01mfrom[39;00m [38;5;21;01meddymotion[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdmri[39;00m [38;5;28;01mimport[39;00m DWI
[1;32m     10[0m [38;5;28;01mfrom[39;00m [38;5;21;01meddymotion[39;00m[38;5;21;01m.[39;00m[38;5;21;01mviz[39;00m [38;5;28;01mimport[39;00m plot_dwi
[1;32m     11[0m [38;5;28;01mfrom[39;00m [38;5;21;01meddymotion[39;00m[38;5;21;01m.[39;00m[38;5;21;01mestimator[39;00m [38;5;28;01mimport[39;00m _advanced_clip

[0;31mModuleNotFoundError[0m: No module named 'eddymotion.dmri'

